#config_version=5

##! mode: ball_indicator
mode:
  start_events: ball_starting
  priority: 130

light_player:
  ball_started{ball==1}: l_ball_1
  ball_started{ball==2}: l_ball_2
  ball_started{ball==3}: l_ball_3
  ball_started{ball==4}: l_ball_4
  ball_started{ball==5}: l_ball_5
