#config_version=5
##! mode: base
mode:
  start_events: ball_started
  priority: 100

variable_player:
  # NOTE: Most of these shots can be grouped, but to me just
  # leads to more inderection later when trying to read this.
  # So I'd rather be explicit here and its easier to follow 

  # Balls (covers top and body rollovers)
  ball_1_hit:
    score: 500
  ball_2_hit:
    score: 500
  ball_3_hit:
    score: 500
  ball_4_hit:
    score: 500
  ball_5_hit:
    score: 500
  ball_6_hit:
    score: 500
  ball_9_hit:
    score: 500
  ball_10_hit:
    score: 500
  ball_11_hit:
    score: 500

  # Slings
  pfs_sling_top_left_active:
    score: 10
  pfs_sling_top_right_active:
    score: 10
  pfs_sling_left_active:
    score: 10
  pfs_sling_right_active:
    score: 10

  # Pop Bumpers
  # TODO: multiplier here
  pfs_popbumper_left_active:
    score: 100
  pfs_popbumper_middle_active:
    score: 100
  pfs_popbumper_right_active:
    score: 100

  # Ball Targets
  pfs_standup_13_7_active:
    score: 500
  pfs_standup_12_15_active:
    score: 500
  pfs_standup_14_8_active:
    score: 500

  # Saucers
  # TODO:


# TODO: Shot group for left saucer
# TODO: Shot group for right saucer

# TODO: coil when special hit and lit

# inverted on/off state for balls
#   state 1: on
#   state 2: off
shot_profiles:
  sp_ball:
    states:
      - name: unlit
        show: "on"
      - name: lit
        show: "off"

shots:
  # Ball 1
  ball_1:
    profile: sp_ball
    switch: pfs_top_lane_rollover_1
    show_tokens:
      light: pfl_top_lane_1
  tri_ball_1:
    hit_events: ball_1_sp_ball_hit
    show_tokens:
      light: pfl_tri_1
  # Ball 2
  ball_2:
    profile: sp_ball
    switch: pfs_top_lane_rollover_2, pfs_inlane_2
    show_tokens:
      light: pfl_top_lane_2, pfl_2
  tri_ball_2:
    hit_events: ball_2_sp_ball_hit
    show_tokens:
      light: pfl_tri_2
  # Ball 3
  ball_3:
    profile: sp_ball
    switch: pfs_top_lane_rollover_3, pfs_inlane_3
    show_tokens:
      light: pfl_top_lane_3, pfl_3
  tri_ball_3:
    hit_events: ball_3_sp_ball_hit
    show_tokens:
      light: pfl_tri_3
  # Ball 4
  ball_4:
    profile: sp_ball
    switch: pfs_top_lane_rollover_4, pfs_outlane_4
    show_tokens:
      light: pfl_top_lane_4, pfl_4
  tri_ball_4:
    hit_events: ball_4_sp_ball_hit
    show_tokens:
      light: pfl_tri_4  
  # Ball 5
  ball_5:
    profile: sp_ball
    switch: pfs_top_lane_rollover_5, pfs_outlane_5
    show_tokens:
      light: pfl_top_lane_5, pfl_5
  tri_ball_5:
    hit_events: ball_5_sp_ball_hit
    show_tokens:
      light: pfl_tri_5
  # Ball 6
  ball_6:
    profile: sp_ball
    switch: pfs_6_rollover
    show_tokens:
      light: pfl_6
  tri_ball_6:
    hit_events: ball_6_sp_ball_hit
    show_tokens:
      light: pfl_tri_6
  # Ball 9
  ball_9:
    profile: sp_ball
    switch: pfs_9_rollover
    show_tokens:
      light: pfl_9
  tri_ball_9:
    hit_events: ball_9_sp_ball_hit
    show_tokens:
      light: pfl_tri_9
  # Ball 10
  ball_10:
    profile: sp_ball
    switch: pfs_10_rollover
    show_tokens:
      light: pfl_10
  tri_ball_10:
    hit_events: ball_10_sp_ball_hit
    show_tokens:
      light: pfl_tri_10
  # Ball 11
  ball_11:
    profile: sp_ball
    switch: pfs_11_rollover
    show_tokens:
      light: pfl_11
  tri_ball_11:
    hit_events: ball_11_sp_ball_hit
    show_tokens:
      light: pfl_tri_11