#config_version=5
##! mode: base
mode:
  start_events: ball_started
  priority: 100

# TODO: Shot group for left saucer
# TODO: Shot group for right saucer
# TODO: coil when special hit and lit
# TODO: special up top?  how does that work?  just top row?

variable_player:
  # NOTE: Most of these shots can be grouped or using tags, 
  # but to me just leads to more inderection later when 
  # trying to read this. So I'd rather be explicit here
  # and have that be easier to follow.  my opinion might change.

  # Lane Rollovers
  ball_1_hit:     { score: 500 }
  ball_2_hit:     { score: 500 }
  ball_3_hit:     { score: 500 }
  ball_4_hit:     { score: 500 }
  ball_5_hit:     { score: 500 }
  
  # Outlanes
  ball_6_hit:     { score: 500 }
  ball_9_hit:     { score: 500 }
  ball_10_hit:    { score: 500 }
  ball_11_hit:    { score: 500 }
  
  # Standup Targets 
  #   NOTE: using switch direct so we can breakout ball tracking below
  pfs_standup_13_7_active:  { score: 500 }
  pfs_standup_12_15_active: { score: 500 }
  pfs_standup_14_8_active:  { score: 500 }

  # Slings
  pfs_sling_top_left_active:  { score: 10 }
  pfs_sling_top_right_active: { score: 10 }
  pfs_sling_left_active:      { score: 10 }
  pfs_sling_right_active:     { score: 10 }

  # Pop Bumpers
  pfs_popbumper_left_active:   { score: 100 * current_player.top_pop_multiplier }
  pfs_popbumper_middle_active: { score: 100 * current_player.mid_pop_multiplier }
  pfs_popbumper_right_active:  { score: 100 * current_player.top_pop_multiplier }

  # Saucers
  pfs_saucer_left_active:  { score: (100 * (5 - current_player.left_col_lit)) + (1000 * current_player.left_col_lit) }
  pfs_saucer_right_active: { score: (100 * (5 - current_player.right_col_lit)) + (1000 * current_player.right_col_lit) }

  # when top and bottom rows are complete, multipliers for pops increases
  top_row_complete: { top_pop_multiplier: { int: 10, action: set } }
  bot_row_complete: { mid_pop_multiplier: { int: 10, action: set } }

  left_col_light_on_hit:
    left_col_lit:
      int: 1
      action: add
  right_col_light_on_hit:
    right_col_lit:
      int: 1
      action: add

# inverted on/off state for balls
#   state 1: on
#   state 2: off
shot_profiles: { sp_ball: { states: [{ name: light_on, show: 'on' }, { name: light_off, show: 'off' }] } }

shots:
  # Lane Rollovers
  ball_1: { profile: sp_ball, switch: 'pfs_top_lane_rollover_1',                show_tokens: { light: 'pfl_top_lane_1'        } }
  ball_2: { profile: sp_ball, switch: 'pfs_top_lane_rollover_2, pfs_inlane_2',  show_tokens: { light: 'pfl_top_lane_2, pfl_2' } }
  ball_3: { profile: sp_ball, switch: 'pfs_top_lane_rollover_3, pfs_inlane_3',  show_tokens: { light: 'pfl_top_lane_3, pfl_3' } }
  ball_4: { profile: sp_ball, switch: 'pfs_top_lane_rollover_4, pfs_outlane_4', show_tokens: { light: 'pfl_top_lane_4, pfl_4' } }
  ball_5: { profile: sp_ball, switch: 'pfs_top_lane_rollover_5, pfs_outlane_5', show_tokens: { light: 'pfl_top_lane_5, pfl_5' } }
  
  # Outlanes
  ball_6:  { profile: sp_ball, switch: pfs_6_rollover,  show_tokens: { light: pfl_6  } }
  ball_9:  { profile: sp_ball, switch: pfs_9_rollover,  show_tokens: { light: pfl_9  } }
  ball_10: { profile: sp_ball, switch: pfs_10_rollover, show_tokens: { light: pfl_10 } }
  ball_11: { profile: sp_ball, switch: pfs_11_rollover, show_tokens: { light: pfl_11 } }
  
  # Targets
  ball_7:  { profile: sp_ball, switch: pfs_standup_13_7,  show_tokens: { light: 'pfl_7'  } }
  ball_8:  { profile: sp_ball, switch: pfs_standup_14_8,  show_tokens: { light: 'pfl_8'  } }
  ball_12: { profile: sp_ball, switch: pfs_standup_12_15, show_tokens: { light: 'pfl_12' } }
  ball_13: { profile: sp_ball, switch: pfs_standup_13_7,  show_tokens: { light: 'pfl_13' } }
  ball_14: { profile: sp_ball, switch: pfs_standup_14_8,  show_tokens: { light: 'pfl_14' } }
  ball_15: { profile: sp_ball, switch: pfs_standup_12_15, show_tokens: { light: 'pfl_15' } }  

# Triangle groupings that give bonuses
shot_groups: 
  top_row:   { shots: 'ball_1, ball_2, ball_3, ball_4, ball_5'    } 
  bot_row:   { shots: 'ball_6, ball_7, ball_8, ball_9'            }
  left_col:  { shots: 'ball_4, ball_6, ball_10, ball_13, ball_15' }
  right_col: { shots: 'ball_5, ball_9, ball_11, ball_14, ball_15' }
  all_balls: { 
               shots: 'ball_1, ball_2, ball_3, ball_4, ball_5, ball_6, 
                       ball_7, ball_8, ball_9, ball_10, ball_11, ball_12,
                       ball_13, ball_14, ball_15' 
             } 

light_player:
  # Center Triangle Lights
  ball_1_sp_ball_hit:   { pfl_tri_1:  on }
  ball_2_sp_ball_hit:   { pfl_tri_2:  on }
  ball_3_sp_ball_hit:   { pfl_tri_3:  on }
  ball_4_sp_ball_hit:   { pfl_tri_4:  on }
  ball_5_sp_ball_hit:   { pfl_tri_5:  on }
  ball_6_sp_ball_hit:   { pfl_tri_6:  on }
  ball_7_sp_ball_hit:   { pfl_tri_7:  on }
  ball_8_sp_ball_hit:   { pfl_tri_8:  on }
  ball_9_sp_ball_hit:   { pfl_tri_9:  on }
  ball_10_sp_ball_hit:  { pfl_tri_10: on }
  ball_11_sp_ball_hit:  { pfl_tri_11: on }
  ball_12_sp_ball_hit:  { pfl_tri_12: on }
  ball_13_sp_ball_hit:  { pfl_tri_13: on }
  ball_14_sp_ball_hit:  { pfl_tri_14: on }
  ball_15_sp_ball_hit:  { pfl_tri_15: on }

  # Pop Bumper Bonuses
  top_row_complete:     { pfl_popbumper_left: on, pfl_popbumper_right: on }
  bot_row_complete:     { pfl_popbumper_middle: on } 

show_player:
  all_balls_complete:
    special:
      manual_advance: true
      start_step: -1
  sw_ball_active:
    special:
      action: advance