#config_version=5

shots:
  # Slings
  sh_sling_left:
    switch: s_sling_left

  sh_sling_right:
    switch: s_sling_right

  sh_sling_top_left:
    switch: s_sling_top_left

  sh_sling_top_right:
    switch: s_sling_top_right

  # Pops
  sh_popbumper_left:
    switch: s_popbumper_left

  sh_popbumper_middle:
    switch: s_popbumper_middle

  sh_popbumper_right:
    switch: s_popbumper_right

  # Balls
  sh_ball_4:
    profile: sp_ball
    switch: s_left_outlane
    advance_events: sh_ball_4_top_hit
    show_tokens:
      leds: l_4
  sh_ball_4_top:
    profile: sp_ball
    switch: s_rollover_left
    advance_events: sh_ball_4_hit
    show_tokens:
      leds: l_4_top

  sh_ball_2:
    profile: sp_ball
    switch: s_left_inlane
    advance_events: sh_ball_2_top_hit
    show_tokens:
      leds: l_2
  sh_ball_2_top:
    profile: sp_ball
    switch: s_rollover_middle_left
    advance_events: sh_ball_2_hit
    show_tokens:
      leds: l_2_top

  sh_ball_1:
    profile: sp_ball
    switch: s_rollover_middle
    show_tokens:
      leds: l_1

  sh_ball_3:
    profile: sp_ball
    switch: s_right_inlane
    advance_events: sh_ball_3_top_hit
    show_tokens:
      leds: l_3
  sh_ball_3_top:
    profile: sp_ball
    switch: s_rollover_middle_right
    advance_events: sh_ball_3_hit
    show_tokens:
      leds: l_3_top

  sh_ball_5:
    profile: sp_ball
    switch: s_right_outlane
    advance_events: sh_ball_5_top_hit
    show_tokens:
      leds: l_5
  sh_ball_5_top:
    profile: sp_ball
    switch: s_rollover_right
    advance_events: sh_ball_5_hit
    show_tokens:
      leds: l_5_top

<<<<<<< HEAD
  sh_saucer_left:
    hit_events: balldevice_bd_saucer_left_ball_entered
  sh_saucer_right:
    hit_events: balldevice_bd_saucer_right_ball_entered

  sh_left_standup:
    switch: s_standup_left
=======
  sh_ball_10:
    profile: sp_ball
    switch: s_toplane_left
    show_tokens:
      leds: l_10

  sh_ball_11:
    profile: sp_ball
    switch: s_toplane_right
>>>>>>> cb252ddfd9f18260d83732368842e956a024ba88
    show_tokens:
      leds: l_13, l_7

  sh_middle_standup:
    switch: s_standup_middle
    show_tokens:
      leds: l_12, l_15

  sh_right_standup:
    switch: s_standup_right
    show_tokens:
<<<<<<< HEAD
      leds: l_8, l_14
=======
      leds: l_9

  sh_left_saucer:
    hit_events: balldevice_bd_saucer_left_ball_entered
  sh_right_saucer:
    hit_events: balldevice_bd_saucer_right_ball_entered
>>>>>>> cb252ddfd9f18260d83732368842e956a024ba88

shot_groups:
  sg_pops_top:
    shots:
      - sh_popbumper_left
      - sh_popbumper_right
  sg_pops_bottom:
    shots:
      - sh_popbumper_middle
  sg_slings:
    shots:
      - sh_sling_top_left
      - sh_sling_top_right
      - sh_sling_left
      - sh_sling_right
  sg_balls:
    shots:
      - sh_ball_1
      - sh_ball_2
      - sh_ball_2_top
      - sh_ball_2
      - sh_ball_3_top
      - sh_ball_4
      - sh_ball_4_top
      - sh_ball_5
      - sh_ball_5_top
      - sh_right_standup
      - sh_left_standup
      - sh_middle_standup
     
  sg_ball_4:
    shots:
      - sh_ball_4
      - sh_ball_4_top

  sg_ball_2:
    shots:
      - sh_ball_2
      - sh_ball_2_top

  sg_ball_3:
    shots:
      - sh_ball_3
      - sh_ball_3_top

  sg_ball_5:
    shots:
      - sh_ball_5
      - sh_ball_5_top

shot_profiles:
  sp_ball:
    states:
      - name: unlit
        show: "on"
      - name: lit
        show: "off"
