#config_version=5

achievements:
  ac_ball_4:
    start_events: sg_ball_4_unlit_hit
    show_when_completed: on
    events_when_started: award_ball_4
    complete_events: award_ball_4
    events_when_completed: left_saucer_ball, award_ball
    show_tokens:
      light: l_triangle_4

  ac_ball_2:
    start_events: sg_ball_2_unlit_hit
    show_when_completed: on
    events_when_started: award_ball_2
    complete_events: award_ball_2
    events_when_completed: award_ball
    show_tokens:
      light: l_triangle_2

  ac_ball_1:
    start_events: sh_ball_1_unlit_hit
    show_when_completed: on
    events_when_started: award_ball_1
    complete_events: award_ball_1
    events_when_completed: award_ball
    show_tokens:
      light: l_triangle_1

  ac_ball_3:
    start_events: sg_ball_3_unlit_hit
    show_when_completed: on
    events_when_started: award_ball_3
    complete_events: award_ball_3
    events_when_completed: award_ball
    show_tokens:
      light: l_triangle_3

  ac_ball_5:
    start_events: sg_ball_5_unlit_hit
    show_when_completed: on
    events_when_started: award_ball_5
    complete_events: award_ball_5
    events_when_completed: right_saucer_ball, award_ball
    show_tokens:
      light: l_triangle_5

  ac_ball_6:
    start_events: sh_ball_6_unlit_hit
    show_when_completed: on
    events_when_started: award_ball_6
    complete_events: award_ball_6
    events_when_completed: left_saucer_ball, award_ball
    show_tokens:
      light: l_triangle_6

  ac_ball_7:
    start_events: sh_left_standup_unlit_hit
    show_when_completed: on
    events_when_started: award_ball_7
    complete_events: award_ball_7
    events_when_completed: award_ball
    show_tokens:
      light: l_triangle_7

  ac_ball_8:
    start_events: sh_right_standup_unlit_hit
    show_when_completed: on
    events_when_started: award_ball_8
    complete_events: award_ball_8
    events_when_completed: award_ball
    show_tokens:
      light: l_triangle_8

  ac_ball_9:
    start_events: sh_ball_9_unlit_hit
    show_when_completed: on
    events_when_started: award_ball_9
    complete_events: award_ball_9
    events_when_completed: right_saucer_ball, award_ball
    show_tokens:
      light: l_triangle_9

  ac_ball_10:
    start_events: sh_ball_10_unlit_hit
    show_when_completed: on
    events_when_started: award_ball_10
    complete_events: award_ball_10
    events_when_completed: left_saucer_ball, award_ball
    show_tokens:
      light: l_triangle_10

  ac_ball_12:
    start_events: sh_middle_standup_unlit_hit
    show_when_completed: on
    events_when_started: award_ball_12
    complete_events: award_ball_12
    events_when_completed: award_ball
    show_tokens:
      light: l_triangle_12

  ac_ball_11:
    start_events: sh_ball_11_unlit_hit
    show_when_completed: on
    events_when_started: award_ball_11
    complete_events: award_ball_11
    events_when_completed: right_saucer_ball, award_ball
    show_tokens:
      light: l_triangle_11

  ac_ball_13:
    start_events: sh_left_standup_unlit_hit
    show_when_completed: on
    events_when_started: award_ball_13
    complete_events: award_ball_13
    events_when_completed: left_saucer_ball, award_ball
    show_tokens:
      light: l_triangle_13

  ac_ball_14:
    start_events: sh_right_standup_unlit_hit
    show_when_completed: on
    events_when_started: award_ball_14
    complete_events: award_ball_14
    events_when_completed: right_saucer_ball, award_ball
    show_tokens:
      light: l_triangle_14

  ac_ball_15:
    start_events: sh_middle_standup_unlit_hit
    show_when_completed: on
    events_when_started: award_ball_15
    complete_events: award_ball_15
    events_when_completed: right_saucer_ball, left_saucer_ball, award_ball
    show_tokens:
      light: l_triangle_15

achievement_groups:
  ag_ball_row_top:
    achievements:
      - ac_ball_1
      - ac_ball_2
      - ac_ball_3
      - ac_ball_4
      - ac_ball_5
    events_when_all_completed: award_top_row_completed

  ag_ball_row_second:
    achievements:
      - ac_ball_6
      - ac_ball_7
      - ac_ball_8
      - ac_ball_9
    events_when_all_completed: award_second_row_completed

  ag_all_balls:
    achievements:
      - ac_ball_1
      - ac_ball_2
      - ac_ball_3
      - ac_ball_4
      - ac_ball_5
      - ac_ball_6
      - ac_ball_7
      - ac_ball_8
      - ac_ball_9
      - ac_ball_10
      - ac_ball_11
      - ac_ball_12
      - ac_ball_13
      - ac_ball_14
      - ac_ball_15
    events_when_all_completed: award_all_balls_completed
