#!/bin/sh

NAME=sureshot
DIR=/code/sureshot
PIDFILE=/var/run/$NAME.pid
DAEMON=/usr/bin/mpf
DAEMON_ARGS=" -tbP"
LOG=/var/log/$NAME.log
common_opts="-q -p $PIDFILE"

# HACK: kind of a hack to do it here, but the OS is limited
# and I'd need to just create another file like this to do it
#
# install module into the kernel we need for USB serial connection
modprobe ftdi_sio

# this worked on this busybox.  normally you have to pass it to the s-s-daemon
cd $DIR

do_start(){
    start-stop-daemon $common_opts -b -S -m -x \
        /bin/sh -- -c "exec $DAEMON $DAEMON_ARGS > $LOG 2>&1"
}

do_stop(){
    start-stop-daemon -K $common_opts 
    rm -f $PIDFILE >/dev/null 2>&1
}

case "$1" in
  start)
        echo -n "Starting daemon: "$NAME
        do_start
        echo "."
        ;;
  stop)
        echo -n "Stopping daemon: "$NAME
        do_stop
        echo "."
        ;;
  restart)
        echo -n "Restarting daemon: "$NAME
        do_stop
        do_start
        echo "."
        ;;
  *)
        echo "Usage: "$1" {start|stop|restart}"
        exit 1
esac

exit 0