#!/bin/sh

DAEMON="sureshot"
PIDFILE="/var/run/$DAEMON.pid"

# HACK: kind of a hack to do it here, but the OS is limited
# and I'd need to just create another file like this to do it
#
# install module into the kernel we need for USB serial connection
modprobe ftdi_sio

# Allow a few customizations from a config file if we want
test -r /etc/default/$DAEMON && . /etc/default/$DAEMON

# move to our working directory
[ -z "$WD" ] && $WD = "/code/sureshot"
cd $WD

# BusyBox' syslogd does not create a pidfile, so pass "-n" in the command line
# and use "-m" to instruct start-stop-daemon to create one.
start() {
    MPF_ARGS="$MPF_ARGS -tbP"

    printf 'Starting %s: ' "$DAEMON" 
    umask 077
    start-stop-daemon -S -q -p $PIDFILE \
        --exec /usr/bin/mpf -- $MPF_ARGS
    
    status=$?
    if [ "$status" -eq 0 ]; then
        echo "OK"
    else
        echo "FAIL"
    fi
    return "$status"
}

stop() {
    printf 'Stopping %s: ' "$DAEMON" 
    start-stop-daemon -K -q -p $PIDFILE
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}
restart() {
    stop
    start
}

:restart() {
    stop
    sleep 1
    start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac