#config_version=5
config:
- config.yaml

switch_player:
  start_event: machine_reset_phase_3
  steps:
    - time: 200ms
      switch: pfs_drain
      action: activate
    - time: 600ms
      switch: cas_start_btn
      action: hit
    - time: 200ms
      switch: pfs_drain
      action: deactivate
    - time: 1s
      switch: pfs_plunger
      action: activate
    - time: 100ms
      switch: pfs_plunger
      action: deactivate
    - time: 1s
      switch: pfs_top_lane_rollover_4
      action: hit
    # - time: 1s
    #   switch: s_left_loop
    #   action: hit
    # - time: 1s
    #   switch: s_right_inlane
    #   action: hit
    # - time: 500ms
    #   switch: s_start
    #   action: hit

    
    #   # Player 2 ball 1
    # - time: 2.5s
    #   switch: s_trough_1
    #   action: activate
    # - time: 1s
    #   switch: s_trough_1
    #   action: deactivate
    # - time: 1s
    #   switch: s_shooter_lane
    #   action: activate
    # - time: 1s
    #   switch: s_ball_launch
    #   action: hit
    # - time: 100ms
    #   switch: s_shooter_lane
    #   action: deactivate
    # - time: 200ms
    #   switch: s_right_inlane
    #   action: hit
    # - time: 200ms
    #   switch: s_right_inlane
    #   action: hit
    # - time: 200ms
    #   switch: s_right_inlane
    #   action: hit
    # - time: 2.5s
    #   switch: s_trough_1
    #   action: activate

    
    #   # Player 1 ball 2
    # - time: 2.5s
    #   switch: s_trough_1
    #   action: activate
    # - time: 1s
    #   switch: s_trough_1
    #   action: deactivate
    # - time: 1s
    #   switch: s_shooter_lane
    #   action: activate
    # - time: 1s
    #   switch: s_ball_launch
    #   action: hit
    # - time: 100ms
    #   switch: s_shooter_lane
    #   action: deactivate
    # - time: 200ms
    #   switch: s_right_inlane
    #   action: hit

    
    #   # Player 2 ball 2
    # - time: 2.5s
    #   switch: s_trough_1
    #   action: activate
    # - time: 1s
    #   switch: s_trough_1
    #   action: deactivate
    # - time: 1s
    #   switch: s_shooter_lane
    #   action: activate
    # - time: 1s
    #   switch: s_ball_launch
    #   action: hit
    # - time: 100ms
    #   switch: s_shooter_lane
    #   action: deactivate
    # - time: 200ms
    #   switch: s_right_inlane
    #   action: hit

    
    #   # Player 1 ball 3
    # - time: 2.5s
    #   switch: s_trough_1
    #   action: activate
    # - time: 1s
    #   switch: s_trough_1
    #   action: deactivate
    # - time: 1s
    #   switch: s_shooter_lane
    #   action: activate
    # - time: 1s
    #   switch: s_ball_launch
    #   action: hit
    # - time: 100ms
    #   switch: s_shooter_lane
    #   action: deactivate
    # - time: 200ms
    #   switch: s_right_inlane
    #   action: hit

    
    #   # Player 2 ball 3
    # - time: 2.5s
    #   switch: s_trough_1
    #   action: activate
    # - time: 1s
    #   switch: s_trough_1
    #   action: deactivate
    # - time: 1s
    #   switch: s_shooter_lane
    #   action: activate
    # - time: 1s
    #   switch: s_ball_launch
    #   action: hit
    # - time: 100ms
    #   switch: s_shooter_lane
    #   action: deactivate
    # - time: 200ms
    #   switch: s_right_inlane
    #   action: hit

    
    # # game end
    # - time: 2.5s
    #   switch: s_trough_1
    #   action: activate

    
    # # new game
    # - time: 2s
    #   switch: s_start
    #   action: hit