#config_version=5

coils:

  ## BACKBOX          :  FP-I/O-3208  #################
  #####################################################
  bbc_reel_10:
    number: 3-0
    default_pulse_ms: 6ms
  bbc_reel_100:
    number: 3-2
    default_pulse_ms: 6ms
  bbc_reel_1000:
    number: 3-3
    default_pulse_ms: 6ms
  bbc_reel_10000:
    number: 3-1
    default_pulse_ms: 6ms
  bbc_gi_lights:
    number: 3-5
    allow_enable: true

  ## CABINET          : FP-I/O-0804  ##################
  #####################################################
  cac_chime_low:
    number: 0-2
    default_pulse_ms: 5ms
  cac_chime_mid:
    number: 0-3
    default_pulse_ms: 5ms
  cac_chime_high:
    number: 0-1
    default_pulse_ms: 5ms
  cac_knocker:
    number: 0-0
    default_pulse_ms: 7ms

  ## PLAYFIELD-LOWER  :  FP-I/O-0804  #################
  #####################################################
  pfc_flipper_left_power:
    number: 1-2
    default_pulse_ms: 15
  pfc_flipper_left_hold:
    number: 1-3
    allow_enable: true
  pfc_flipper_right_power:
    number: 1-0
    default_pulse_ms: 15
  pfc_flipper_right_hold:
    number: 1-1
    allow_enable: true

  ## PLAYFIELD-UPPER  :  FP-I/O-3208  #################
  #####################################################
  pfc_drain_eject:
    number: 2-0
    default_pulse_ms: 20
  pfc_sling_left:
    number: 2-6
    default_pulse_power: 0.625
  pfc_sling_right:
    number: 2-1
    default_pulse_power: 0.625
  pfc_saucer_left:
    number: 2-7
    default_pulse_ms: 9ms
  pfc_saucer_right:
    number: 2-2
    default_pulse_ms: 9ms
  pfc_popbumper_left:
    number: 2-5
    default_pulse_power: 0.5
  pfc_popbumper_middle:
    number: 2-3
    default_pulse_power: 0.5
  pfc_popbumper_right:
    number: 2-4
    default_pulse_power: 0.5
