#config_version=5

config:
  - platform_fast.yaml
  - hardware_cabinet.yaml
  - hardware_playfield.yaml
  - mechs.yaml
  - virtual.yaml

modes:
  - all_balls_completed
  - base
  - ball_awards
  - bonus
  - top_row_completed
  - saucer
  - second_row_completed
  - all_balls_completed

game:
  balls_per_game: 5
