#config_version=5
mpf:
  report_crashes: never
  default_light_hw_update_hz: 30

config:
  - coils.yaml
  - infolights.yaml
  - lights.yaml
  - mechs.yaml
  - platform_fast.yaml
  - switches.yaml

# -- Player Variables ---------
player_vars:
  top_pop_multiplier:
    initial_value: 1
  mid_pop_multiplier:
    initial_value: 1
  left_col_lit:
    initial_value: 0
  right_col_lit:
    initial_value: 0
  total_balls_collected:
    initial_value: 0

# -- Modes --------------------
modes:
  - base
  - bonus
  - match

show_player:
  game_started:
    general_illumination: play
    game_over_blink: stop
    match_blank: play
  game_ending:
    match_blank: stop
    game_over_tone:
      loops: 0
  game_ended:
    game_over_blink: play
  ball_search_started:
    trough_blink: play
  ball_search_stopped:
    trough_blink: stop

machine:
  # TODO: ADD BACK: if we want ballsearch logic
  min_balls: 0

game:
  balls_per_game: 5 # TODO: switch back to 5 when done with bonus testing
  max_players: 1 # TODO: switch back once stable

playfields:
  playfield:
    tags: default
    default_source_device: bd_shooter_lane
# TODO: ADD BACK
#    enable_ball_search: true
#    ball_search_disable_events: balldevice_playfield_ball_enter

# -- Virtual ------------------
virtual_platform_start_active_switches: pfs_drain