#config_version=5

config:
  - platform_fast.yaml
  - hardware_backbox.yaml
  - hardware_cabinet.yaml
  - hardware_playfield.yaml
  - mechs.yaml
  - virtual.yaml

mpf: 
  report_crashes: never
  default_light_hw_update_hz: 30

modes:
  - all_balls_completed
  - base
  - ball_awards
  - ball_indicator
  - bonus
  - match
  - top_row_completed
  - saucer
  - second_row_completed
  - all_balls_completed
  - switch_light_control

show_player:
  game_started: 
    general_illumination: play
    game_over_blink: stop
    match_blank: play
    
  game_ending:
    match_blank: stop
    game_over_tone:
      loops: 0
  game_ended:
    game_over_blink: play
  ball_search_started:
    trough_blink: play
  ball_search_stopped:
    trough_blink: stop

game:
  balls_per_game: 5

playfields:
  playfield:
    tags: default
    default_source_device: bd_plunger_lane
    enable_ball_search: true
    ball_search_disable_events: balldevice_playfield_ball_enter
    console_log: basic
    file_log: basic

