#config_version=5

config:
  - platform_fast.yaml
  - hardware_backbox.yaml
  - hardware_cabinet.yaml
  - hardware_playfield.yaml
  - mechs.yaml
  - virtual.yaml

mpf: 
  report_crashes: never

modes:
  - all_balls_completed
  - base
  - ball_awards
  - ball_indicator
  - bonus
  - match
  - match_spin
  - top_row_completed
  - saucer
  - second_row_completed
  - all_balls_completed
  - switch_light_control

show_player:
  game_started: general_illumination

game:
  balls_per_game: 5
  allow_start_with_loose_balls: true
