#config_version=5

config:
  - platform_fast.yaml
  - hardware_cabinet.yaml
  - hardware_playfield.yaml
  - mechs.yaml
  - virtual.yaml

modes:
  - base
  - ball_awards
  - top_row_completed

game:
  balls_per_game: 5
