#config_version=5

switches:
  s_left_flipper:
    number: 0 # TODO: fix with real hardware
    tags: left_flipper
  s_right_flipper:
    number: 1 # TODO: fix with real hardware
    tags: right_flipper
  coils:
  c_flipper_left_main:
    number: 0  # again, these numbers will probably be different for you
  c_flipper_left_hold:
    number: 1  # check your platform-specific documentation for the actual numbers
    allow_enable: true
  c_flipper_right_main:
    number: 2
  c_flipper_right_hold:
    number: 3
    allow_enable: true