#config_version=5
mpf:
  report_crashes: never
  default_light_hw_update_hz: 30

config:
  - coils.yaml
  - lights.yaml
  - mechs.yaml
  - platform_fast.yaml
  - switches.yaml

# -- Modes --------------------
modes:
  - base
  - bonus
  - match

show_player:
  game_started:
    general_illumination: play
    game_over_blink: stop
    match_blank: play
  game_ending:
    match_blank: stop
    game_over_tone:
      loops: 0
  game_ended:
    game_over_blink: play
  ball_search_started:
    trough_blink: play
  ball_search_stopped:
    trough_blink: stop

machine:
  # TODO: ADD BACK: if we want ballsearch logic
  min_balls: 0

game:
  balls_per_game: 5

playfields:
  playfield:
    tags: default
    default_source_device: bd_shooter_lane
# TODO: ADD BACK
#    enable_ball_search: true
#    ball_search_disable_events: balldevice_playfield_ball_enter
    console_log: basic
    file_log: basic

# -- Virtual ------------------
virtual_platform_start_active_switches: s_drain
