#config_version=5

hardware:
  platform: fast
  driverboards: fast

fast:
  ports: autodetect
  # These are defaults, but mpfls thinks they are required
  default_normal_debounce_open: 10ms
  default_normal_debounce_close: 10ms
  default_quick_debounce_open: 2ms
  default_quick_debounce_close: 2ms

config:
  - hardware_playfield.yaml
