#config_version=5

switches:
  # Lower playfield 0804
  # TODO: Adjust ring numbers
  s_left_flipper_eos:
    number: 0-0
    tags: left_flipper
  s_right_flipper_eos:
    number: 0-1
    tags: right_flipper
  s_drain:
    number: 0-4
  s_plunger:
    number: 0-5
  s_left_inlane:
    number: 0-2
    tags: playfield_active
  s_left_outlane:
    number: 0-3
    tags: playfield_active
  s_right_inlane:
    number: 0-7
    tags: playfield_active
  s_right_outlane:
    number: 0-6
    tags: playfield_active

coils:
  # Lower playfield 0804
  # TODO: Adjust ring numbers
  c_flipper_left_main:
    number: 0-2
  c_flipper_left_hold:
    number: 0-3
    allow_enable: true
  c_flipper_right_main:
    number: 0-0
  c_flipper_right_hold:
    number: 0-1
    allow_enable: true
  # Upper playfield 3208
  # TODO: Adjust ring numbers
  c_drain_eject:
    number: 1-0
    default_pulse_ms: 20
