#config_version=5

switches:
  # Lower playfield 0804
  s_left_flipper_eos:
    number: 1-0
    tags: left_flipper
  s_right_flipper_eos:
    number: 1-1
    tags: right_flipper
  s_drain:
    number: 1-4
  s_plunger:
    number: 1-5
  s_left_inlane:
    number: 1-2
    tags: playfield_active
  s_left_outlane:
    number: 1-3
    tags: playfield_active
  s_right_inlane:
    number: 1-7
    tags: playfield_active
  s_right_outlane:
    number: 1-6
    tags: playfield_active

  # Upper playfield 3208
  s_sling_left:
    number: 2-0
  s_sling_right:
    number: 2-15
  s_midlane_left:
    number: 2-2
    tags: playfield_active
  s_standup_left:
    number: 2-4
    tags: playfield_active
  s_standup_right:
    number: 2-13
    tags: playfield_active
  s_midlane_right:
    number: 2-14
    tags: playfield_active
  s_toplane_left:
    number: 2-7
    tags: playfield_active
  s_sling_top_left:
    number: 2-5
    tags: playfield_active
  s_standup_middle:
    number: 2-28
    tags: playfield_active
  s_sling_top_right:
    number: 2-11
    tags: playfield_active
  s_toplane_right:
    number: 2-12
    tags: playfield_active
  s_saucer_left:
    number: 2-6
  s_popbumper_left:
    number: 2-3
  s_popbumper_middle:
    number: 2-1
  s_popbumper_right:
    number: 2-9
  s_saucer_right:
    number: 2-10
  s_rollover_left:
    number: 2-26
    tags: playfield_active
  s_rollover_middle_left:
    number: 2-27
    tags: playfield_active
  s_rollover_middle:
    number: 2-24
    tags: playfield_active
  s_rollover_middle_right:
    number: 2-25
    tags: playfield_active
  s_rollover_right:
    number: 2-8
    tags: playfield_active

coils:
  # Lower playfield 0804
  c_flipper_left_main:
    number: 1-2
    default_pulse_ms: 15
  c_flipper_left_hold:
    number: 1-3
    allow_enable: true
  c_flipper_right_main:
    number: 1-0
    default_pulse_ms: 15
  c_flipper_right_hold:
    number: 1-1
    allow_enable: true
  # Upper playfield 3208
  c_drain_eject:
    number: 2-0
    default_pulse_ms: 20
  c_sling_left:
    number: 2-6
    default_pulse_power: 0.625
  c_sling_right:
    number: 2-1
    default_pulse_power: 0.625
  c_saucer_left:
    number: 2-7
    default_pulse_ms: 9ms
  c_saucer_right:
    number: 2-2
    default_pulse_ms: 9ms
  c_popbumper_middle:
    number: 2-3
    default_pulse_ms: 3ms
  c_popbumper_left:
    number: 2-5
    default_pulse_ms: 3ms
  c_popbumper_right:
    number: 2-4
    default_pulse_ms: 3ms

lights:
  # Inserts
  l_2_top:
    previous: l_special_top
    type: grb
  l_3_top:
    previous: l_popbumper_right
    type: grb
  l_4_top:
    previous: l_2_top
    type: grb
  l_5_top:
    number: 1-0
    type: grb
  l_special_top:
    previous: l_1
    type: grb
  
  l_1:
    previous: l_3_top
    type: grb
  l_2:
    previous: l_4
    type: grb
  l_3:
    previous: l_8
    type: grb
  l_4:
    previous: l_13
    type: grb
  l_5:
    previous: l_3
    type: grb
  l_6:
    previous: l_10
    type: grb
  l_7:
    previous: l_2
    type: grb
  l_8:
    previous: l_triangle_11
    type: grb
  l_9:
    previous: l_14
    type: grb
  l_10:
    previous: l_popbumper_left
    type: grb
  l_11:
    previous: l_9
    type: grb
  l_12:
    previous: l_popbumper_middle
    type: grb
  l_13:
    previous: l_6
    type: grb
  l_14:
    previous: l_5
    type: grb
  l_15:
    previous: l_12 
    type: grb

  # Trough
  l_trough_1:
    previous: l_7
    type: grb
  l_trough_2:
    previous: l_trough_1
    type: grb
  l_trough_3:
    previous: l_trough_2
    type: grb
  l_trough_4:
    previous: l_trough_3
    type: grb
  l_trough_5:
    previous: l_trough_4
    type: grb
  l_trough_6:
    previous: l_trough_5
    type: grb

  # Triangle
  l_triangle_1:
    previous: l_triangle_2
    type: grb
  l_triangle_2:
    previous: l_15
    type: grb
  l_triangle_3:
    previous: l_triangle_1
    type: grb
  l_triangle_4:
    previous: l_triangle_6
    type: grb
  l_triangle_5:
    previous: l_triangle_3
    type: grb
  l_triangle_6:
    previous: l_triangle_10
    type: grb
  l_triangle_7:
    previous: l_triangle_8
    type: grb
  l_triangle_8:
    previous: l_triangle_9
    type: grb
  l_triangle_9:
    previous: l_triangle_5
    type: grb
  l_triangle_10:
    previous: l_triangle_13
    type: grb
  l_triangle_11:
    previous: l_triangle_14
    type: grb
  l_triangle_12:
    previous: l_triangle_7
    type: grb
  l_triangle_13:
    previous: l_triangle_15
    type: grb
  l_triangle_14:
    previous: l_triangle_12
    type: grb
  l_triangle_15:
    previous: l_trough_6
    type: grb
  
  # Saucers
  l_special_left:
    previous: l_4_top
    type: grb
  l_special_right:
    previous: l_11
    type: grb

  # Pops
  l_popbumper_left:
    previous: l_special_left
    type: grb
  l_popbumper_middle:
    previous: l_triangle_4
    type: grb
  l_popbumper_right:
    previous: l_5_top
    type: grb

  # GI
  l_gi_rollover_6:
    number: 0-0
    type: rgb
  l_gi_rollover_5:
    previous: l_gi_rollover_6
    type: rgb
  l_gi_rollover_4:
    previous: l_gi_rollover_5
    type: rgb
  l_gi_rollover_3:
    previous: l_gi_rollover_4
    type: rgb
  l_gi_rollover_2:
    previous: l_gi_rollover_3
    type: rgb
  l_gi_rollover_1:
    previous: l_gi_rollover_2
    type: rgb

  l_gi_sling_top_left:
    previous: l_gi_rollover_1
    type: rgb

  l_gi_standup_left:
    previous: l_gi_sling_top_left
    type: rgb

  l_gi_sling_left_1:
    previous: l_gi_standup_left
    type: rgb
  l_gi_sling_left_2:
    previous: l_gi_sling_left_1
    type: rgb

  l_gi_sling_right_2:
    previous: l_gi_sling_left_2
    type: rgb
  l_gi_sling_right_1:
    previous: l_gi_sling_right_2
    type: rgb

  l_gi_standup_right:
    previous: l_gi_sling_right_1
    type: rgb

  l_gi_sling_top_right:
    previous: l_gi_standup_right
    type: rgb

light_settings:
  default_color_correction_profile: correction_profile_warm_white
  color_correction_profiles:
    correction_profile_warm_white:
      whitepoint: [0.93, 0.92, 0.84]
