#config_version=5

switches:
  s_score_zero_10:
    number: 3-0
  s_score_zero_100:
    number: 3-2
  s_score_zero_1000:
    number: 3-3
  s_score_zero_10000:
    number: 3-1

coils:
  # Backbox 3208
  c_score_inc_10:
    number: 3-0
    default_pulse_power: 0.5
  c_score_inc_100:
    number: 3-2
    default_pulse_power: 0.5
  c_score_inc_1000:
    number: 3-3
    default_pulse_power: 0.5
  c_score_inc_10000:
    number: 3-1
    default_pulse_power: 0.5
  c_gi_lights:
    number: 3-5
    allow_enable: true

lights:
  # Ball indicators
  l_ball_1:
    number: 2-11
    type: grb
  l_ball_2:
    number: 2-12
    type: grb
  l_ball_3:
    number: 2-13
    type: grb
  l_ball_4:
    number: 2-14
    type: grb
  l_ball_5:
    number: 2-15
    type: grb

  l_gameover:
    number: 2-10
    type: grb

  # Match
  l_match_00:
    number: 2-9
    type: grb
  l_match_10:
    number: 2-8
    type: grb
  l_match_20:
    number: 2-7
    type: grb
  l_match_30:
    number: 2-6
    type: grb
  l_match_40:
    number: 2-5
    type: grb
  l_match_50:
    number: 2-4
    type: grb
  l_match_60:
    number: 2-3
    type: grb
  l_match_70:
    number: 2-2
    type: grb
  l_match_80:
    number: 2-1
    type: grb
  l_match_90:
    number: 2-0
    type: grb

  # GI
  l_backbox_gi:
    number: c_gi_lights
    platform: drivers