#config_version=5

switches:
  s_score_zero_10:
    number: 3-1
  s_score_zero_100:
    number: 3-2
  s_score_zero_1000:
    number: 3-0

coils:
  # Backbox 3208
  c_score_inc_10:
    number: 3-2
  c_score_inc_100:
    number: 3-0
    default_pulse_power: 0.5
  c_score_inc_1000:
    number: 3-1

lights:
  # Ball indicators
  l_ball_1:
    number: 2-0
    type: grb
  l_ball_2:
    previous: l_ball_1
    type: grb
  l_ball_3:
    previous: l_ball_2
    type: grb
  l_ball_4:
    previous: l_ball_3
    type: grb
  l_ball_5:
    previous: l_ball_4
    type: grb
