#config_version=5

switches:
  # Lower playfield 0804
  s_left_flipper_eos:
    number: 1-0
    tags: left_flipper
  s_right_flipper_eos:
    number: 1-1
    tags: right_flipper
  s_drain:
    number: 1-4
  s_plunger:
    number: 1-5
  s_left_inlane:
    number: 1-2
    tags: playfield_active
  s_left_outlane:
    number: 1-3
    tags: playfield_active
  s_right_inlane:
    number: 1-7
    tags: playfield_active
  s_right_outlane:
    number: 1-6
    tags: playfield_active
  # Upper playfield 3208
  s_sling_left:
    number: 2-0
  s_sling_right:
    number: 2-2
  s_midlane_left:
    number: 2-4
    tags: playfield_active
  s_standup_left:
    number: 2-5
    tags: playfield_active
  s_standup_right:
    number: 2-6
    tags: playfield_active
  s_midlane_right:
    number: 2-7
    tags: playfield_active
  s_toplane_left:
    number: 2-8
    tags: playfield_active
  s_sling_top_left:
    number: 2-21
    tags: playfield_active
  s_standup_middle:
    number: 2-9
    tags: playfield_active
  s_sling_top_right:
    number: 2-22
    tags: playfield_active
  s_toplane_right:
    number: 2-10
    tags: playfield_active
  s_saucer_left:
    number: 2-11
  s_popbumper_left:
    number: 2-12
  s_popbumper_middle:
    number: 2-13
  s_popbumper_right:
    number: 2-14
  s_saucer_right:
    number: 2-15
  s_rollover_left:
    number: 2-16
    tags: playfield_active
  s_rollover_middle_left:
    number: 2-17
    tags: playfield_active
  s_rollover_middle:
    number: 2-18
    tags: playfield_active
  s_rollover_middle_right:
    number: 2-19
    tags: playfield_active
  s_rollover_right:
    number: 2-20
    tags: playfield_active

coils:
  # Lower playfield 0804
  # TODO: Adjust ring numbers
  c_flipper_left_main:
    number: 1-2
  c_flipper_left_hold:
    number: 1-3
    allow_enable: true
  c_flipper_right_main:
    number: 1-0
  c_flipper_right_hold:
    number: 1-1
    allow_enable: true
  # Upper playfield 3208
  c_drain_eject:
    number: 2-0
    default_pulse_ms: 20
  c_sling_left:
    number: 2-1
  c_sling_right:
    number: 2-2
  c_saucer_left:
    number: 2-3
  c_saucer_right:
    number: 2-4
  c_popbumper_left:
    number: 2-5
  c_popbumper_middle:
    number: 2-6
  c_popbumper_right:
    number: 2-7
