#config_version=5

switches:
  s_left_flipper:
    number: 0-1
    tags: left_flipper
  s_right_flipper:
    number: 0-0
    tags: right_flipper
  s_start:
    number: 0-2
    tags: start

coils:
  c_knocker:
    number: 00
    default_pulse_ms: 20
    max_pulse_ms: 100
