#config_version=5

switches:
  s_score_zero_10:
    number: 3-1
  s_score_zero_100:
    number: 3-2
  s_score_zero_1000:
    number: 3-0

coils:
  # Backbox 3208
  c_score_inc_10:
    number: 3-2
  c_score_inc_100:
    number: 3-0
    default_pulse_power: 0.5
  c_score_inc_1000:
    number: 3-1
