#config_version=5

switches:
  s_score_zero_10:
    number: 3-0
  s_score_zero_100:
    number: 3-2
  s_score_zero_1000:
    number: 3-3
  s_score_zero_10000:
    number: 3-1

coils:
  # Backbox 3208
  c_score_inc_10:
    number: 3-0
    default_pulse_power: 0.5
  c_score_inc_100:
    number: 3-2
    default_pulse_power: 0.5
  c_score_inc_1000:
    number: 3-3
    default_pulse_power: 0.5
  c_score_inc_10000:
    number: 3-1
    default_pulse_power: 0.5

lights:
  # Ball indicators
  l_ball_1:
    number: 2-0
    type: grb
  l_ball_2:
    previous: l_ball_1
    type: grb
  l_ball_3:
    previous: l_ball_2
    type: grb
  l_ball_4:
    previous: l_ball_3
    type: grb
  l_ball_5:
    previous: l_ball_4
    type: grb

  l_gameover:
    previous: l_ball_5
    type: grb

  # Match
  l_match_00:
    previous: l_gameover
    type: grb
  l_match_10:
    previous: l_match_00
    type: grb
  l_match_20:
    previous: l_match_10
    type: grb
  l_match_30:
    previous: l_match_20
    type: grb
  l_match_40:
    previous: l_match_30
    type: grb
  l_match_50:
    previous: l_match_40
    type: grb
  l_match_60:
    previous: l_match_50
    type: grb
  l_match_70:
    previous: l_match_60
    type: grb
  l_match_80:
    previous: l_match_70
    type: grb
  l_match_90:
    previous: l_match_80
    type: grb
