#config_version=5
info_lights:
  # NOTE: not using match_XX feature here.  I want to fire the knocker and
  # wasn't immediately easly for me to articulate that configuration given 'winners'
  # I already had a pretty simple match mode that blinks match and knocks so keeing that.
  ball_1:
    light: bbl_ball_in_play_1
  ball_2:
    light: bbl_ball_in_play_2
  ball_3:
    light: bbl_ball_in_play_3
  ball_4:
    light: bbl_ball_in_play_4
  ball_5:
    light: bbl_ball_in_play_5
  game_over:
    light: bbl_gameover