#config_version=5

flippers:
  left_flipper:
    main_coil: pfc_flipper_left_power
    hold_coil: pfc_flipper_left_hold
    activation_switch: cas_left_flipper_btn
    eos_switch: pfs_left_flipper_eos
  right_flipper:
    main_coil: pfc_flipper_right_power
    hold_coil: pfc_flipper_right_hold
    activation_switch: cas_right_flipper_btn
    eos_switch: pfs_right_flipper_eos

ball_devices:
  bd_drain:
    ball_switches: pfs_drain
    eject_coil: pfc_drain_eject
    eject_targets: bd_shooter_lane
    tags: drain, home, trough
    eject_timeouts: 3s
  bd_shooter_lane:
    ball_switches: pfs_plunger
    mechanical_eject: true
    eject_timeouts: 5s
  bd_saucer_left:
    ball_switches: pfs_saucer_left
    eject_coil: pfc_saucer_left
    eject_timeouts: 2s
    entrance_count_delay: 500ms
  bd_saucer_right:
    ball_switches: pfs_saucer_left
    eject_coil: pfc_saucer_right
    eject_timeouts: 2s
    entrance_count_delay: 500ms
