#config_version=5

flippers:
  left_flipper:
    main_coil: pfc_flipper_left_power
    hold_coil: pfc_flipper_left_hold
    activation_switch: cas_left_flipper_btn
    eos_switch: pfs_left_flipper_eos
  right_flipper:
    main_coil: pfc_flipper_right_power
    hold_coil: pfc_flipper_right_hold
    activation_switch: cas_right_flipper_btn
    eos_switch: pfs_right_flipper_eos

ball_devices:
  bd_drain:
    ball_switches: pfs_drain
    eject_coil: pfc_drain_eject
    eject_targets: bd_shooter_lane
    tags: drain, home, trough
    eject_timeouts: 3s
  bd_shooter_lane:
    ball_switches: pfs_plunger
    mechanical_eject: true
    eject_timeouts: 5s
  bd_saucer_left:
    ball_switches: pfs_saucer_left
    eject_coil: pfc_saucer_left
    eject_timeouts: 2s
    entrance_count_delay: 1s
  bd_saucer_right:
    ball_switches: pfs_saucer_right
    eject_coil: pfc_saucer_right
    eject_timeouts: 2s
    entrance_count_delay: 1s

autofire_coils:
  ac_slightshot_left:
    coil: pfc_sling_left
    switch: pfs_sling_left
  ac_slightshot_right:
    coil: pfc_sling_right
    switch: pfs_sling_right
  ac_popbumper_left:
    coil: pfc_popbumper_left
    switch: pfs_popbumper_left
  ac_popbumper_middle:
    coil: pfc_popbumper_middle
    switch: pfs_popbumper_middle
  ac_popbumper_right:
    coil: pfc_popbumper_right
    switch: pfs_popbumper_right

score_reels:
  sr_10:
    coil_inc: bbc_reel_10
    switch_0: bbs_reel_zero_10
    repeat_pulse_time: 150ms
    hw_confirm_time: 10ms
  sr_100:
    coil_inc: bbc_reel_100
    switch_0: bbs_reel_zero_100
    repeat_pulse_time: 150ms
    hw_confirm_time: 10ms
  sr_1000:
    coil_inc: bbc_reel_1000
    switch_0: bbs_reel_zero_1000
    repeat_pulse_time: 150ms
    hw_confirm_time: 10ms
  sr_10000:
    coil_inc: bbc_reel_10000
    switch_0: bbs_reel_zero_10000
    repeat_pulse_time: 150ms
    hw_confirm_time: 10ms

score_reel_groups:
  srg_score:
    reels: sr_10000, sr_1000, sr_100, sr_10, None
    tags: player1, player2, player3, player4
    chimes: cac_chime_high, cac_chime_low, cac_chime_mid, cac_chime_high, None