#config_version=5

flippers:
  left_flipper:
    main_coil: c_flipper_left_main
    hold_coil: c_flipper_left_hold
    activation_switch: s_left_flipper
    eos_switch: s_left_flipper_eos
    debug: true
  right_flipper:
    main_coil: c_flipper_right_main
    hold_coil: c_flipper_right_hold
    activation_switch: s_right_flipper
    eos_switch: s_right_flipper_eos
    debug: true

ball_devices:
  bd_drain:
    ball_switches: s_drain
    # TODO: Add once eject coil is wired
    # eject_coil: c_drain_eject
    mechanical_eject: true
    eject_targets: bd_plunger_lane
    tags: drain, home, trough
    eject_timeouts: 3s
    debug: true
  bd_plunger_lane:
    ball_switches: s_plunger
    mechanical_eject: true
    eject_timeouts: 5s

playfields:
  playfield:
    tags: default
    default_source_device: bd_plunger_lane
