#config_version=5

flippers:
  left_flipper:
    main_coil: c_flipper_left_main
    hold_coil: c_flipper_left_hold
    activation_switch: s_left_flipper
    eos_switch: s_left_flipper_eos
    debug: true
  right_flipper:
    main_coil: c_flipper_right_main
    hold_coil: c_flipper_right_hold
    activation_switch: s_right_flipper
    eos_switch: s_right_flipper_eos
    debug: true

ball_devices:
  bd_drain:
    ball_switches: s_drain
    eject_coil: c_drain_eject
    eject_targets: bd_plunger_lane
    tags: drain, home, trough
    eject_timeouts: 3s
    debug: true
  bd_plunger_lane:
    ball_switches: s_plunger
    mechanical_eject: true
    eject_timeouts: 5s
  bd_saucer_left:
    ball_switches: s_saucer_left
    eject_coil: c_saucer_left
  bd_saucer_right:
    ball_switches: s_saucer_right
    eject_coil: c_saucer_right

autofire_coils:
  ac_slightshot_left:
    coil: c_sling_left
    switch: s_sling_left
  ac_slightshot_right:
    coil: c_sling_right
    switch: s_sling_right
  ac_popbumper_left:
    coil: c_popbumper_left
    switch: s_popbumper_left
  ac_popbumper_middle:
    coil: c_popbumper_middle
    switch: s_popbumper_middle
  ac_popbumper_right:
    coil: c_popbumper_right
    switch: s_popbumper_right

playfields:
  playfield:
    tags: default
    default_source_device: bd_plunger_lane
