#config_version=5

##! mode: all_balls_completed
mode:
  start_events: award_all_balls_completed
  priority: 250

shots:
  sh_special_left:
    profile: sp_specials
    hit_events: balldevice_bd_saucer_left_ball_entered
    show_tokens:
      leds: l_special_left

  sh_special_top:
    profile: sp_specials
    switch: s_rollover_middle
    show_tokens:
      leds: l_special_top

  sh_special_right:
    profile: sp_specials
    hit_events: balldevice_bd_saucer_right_ball_entered
    advance_events: mode_all_balls_completed_started
    show_tokens:
      leds: l_special_right

shot_profiles:
  sp_specials:
    advance_on_hit: false
    states:
      - name: off
        show: off
      - name: lit
        show: on

shot_groups:
  sg_specials:
    shots: sh_special_right, sh_special_left, sh_special_top
    rotate_events: sg_slings_hit

coil_player:
  sg_specials_lit_hit: c_knocker
